### ISSUE TITLE
Puppet v1.18 Todo-list

### ISSUE THREAD

**Issue by huan** [wechaty/puppet#186]
- [x] add handle https://github.com/wechaty/puppet/issues/181#issuecomment-1061701290
- [x] add talkerId & listenerId wechaty/puppet#187
- [x] fix dirty deadloop wechaty/wechaty#2379

**Comment by huan** [comment]
All done.
